---
title: "ホーム"
author:
  - 上條良夫（早稲田大学）
  - 矢内勇生（高知工科大学）
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, fig.align = 'center')
```


<br>

## R で学ぶゲーム理論

このサイトは、上條・矢内によって執筆された<a href="https://www.asakura.co.jp/detail.php?book_code=27024">「R で学ぶゲーム理論」（朝倉書店）</a>の紹介をかねたサポートページです。
本書の最大の特徴は、rgamer というゲーム理論の分析を自動化するアプリの力を最大限活用することで、従来のゲーム理論の教科書とは異なる方法で、ゲーム理論の楽しさ・有用さを伝えている点です。
本書の特徴を理解していただくために、本書の序論に記された読者へのメッセージを以下に掲載します。

<br>
<br>


## 読者へのメッセージ


<font size = "5">数学は嫌いだが, ゲーム理論を学習したいあなたへ.</font>
安心してほしい.
数学が苦手な人であってもゲーム理論の基礎を習得し, かつ, ゲーム理論の面白さを味わうこと ができるよう, 著者二人で全力を尽くした.
私たちが本書のために開発した rgamer と いう R パッケージは, あなた自身がゲームを「作る」ことを可能としてくれる.
実際にゲームを作る体験を通じて, ゲームの定義やゲームの答えを見つけることの意味に ついて, 数式に頼ることなく理解できるはずだ.
特に, rgamer に備わったシミュレーション機能を使えば, ややこしい計算の代わりに直感を働かせることによって, ゲームの答えとされる均衡のイメージを的確に捉えることができるだろう.

<br>

<font size = "5">ゲーム理論の理論的背景よりも, ゲーム理論からどんな予測が得られるのかを知りたいあなたへ.</font>
ゲーム理論の裾野が広がるにつれて, 理論の詳細にはさほど関心はないが, ゲーム理論がどんな予測を生み出すのかに興味を持つ人が増えてきた.
そのような人たちは, ゲーム理論には統計学や機械学習のようにややこしい計算を自動的に行っ てくれるアプリ (ソフト) はないのか, と不思議に思うだろう.
実は, まさに rgamer が そのようなアプリなのだ.
rgamer は, ゲーム理論が扱う基本的なゲームを自動的に解析する機能を持っている.
必要なコードを入力すれば解析結果が得られ, それをゲーム理論的な予測として用いることができる.
シミュレーション機能も備えているので, 結果が運に左右されるようなゲームについても, その確率的な振る舞いを確かめることができる.

<br>

<font size = "5">ゲーム理論を深く理解したいあなたへ.</font>
ゲーム理論を学習したことがある人に対しても, 本書が新しい体験を提供することは間違いない.
コンピュータプログラムを書 くことによってゲームを解くという行為は, 紙とペンを用いて答えを計算する伝統的 な学習で得られるものとは異なる理解を促す.
プログラムしたパラメタの値を変える という軽微で容易なコード修正によって, 読者は自分が興味を持った状況に対する理 論予測を即座に得ることができる.
つまり, モデルで「遊ぶ」ことができるのだ.
そのような遊びを通して新しいインプリケーションが得られることもあるだろう.
シミュレーション機能を利用すれば人々の選択が変化するダイナミクスを観察することも できる.
それにより, 均衡はどのように達成されるか, その均衡にいかなる解釈を与 えることが可能か, というゲーム理論の専門的側面についての理解をも深めることができる.

<br>

<font size = "5">データサイエンスとゲーム理論を合わせて学習したいあなたへ.</font>
rgamer は R のパッケージである.
よって, rgamer を使用する読者は, 必然的に R そのものの操作にもな じむことになる.
従来, ゲーム理論のように紙とペンを用いて数学的に答えを導出する理論の勉強と, データ分析のようにコンピュータプログラムを書くことによって実際に観測されたデータを処理する経験的分析の勉強は, まったくの別物として扱われてきた.
rgamer は, いまや統計分析の標準的ツールとなった R を, ゲーム理論の解析に使うために開発されたパッケージである.
R を用いることで，データ分析で発達した可視化やシミュレーションなどの道具をゲーム理論の学習にも役立てることができる.
可視化やシミュレーションになじみがない読者は, 本書でゲーム理論を学びながら, それらの道具の使い方を身につけることができる.
それにより, データサイエンスの理解も促される.
rgamer を利用することで, ゲーム理論とデータ分析の垣根が低くなるだろう.

<br>

<font size = "5">ゲーム理論を教えるあなたへ.</font>
ゲーム理論をある程度しっかりと教えようとしたと きに, 数学嫌いの学生, あるいは数学の勉強をあまりしてこなかった学生への教育方法に悩んだ経験はないだろうか.
とりわけ,「文系」学部でゲーム理論を教える際には, そのような困難に直面することが多いだろう.
rgamer は, そんなあなたの授業を助ける様々な機能を提供する.
rgamer がゲームを自動的に解いてくれるので, 均衡計算に必要な数学的なテクニックの説明に費やしていた時間を, モデルの妥当性や結果の解釈 といった, より本質的な議論に回すことができる.
rgamer を用いることで, これまでとまったく異なる授業を展開することができるようになるのだ.
さらに, rgamer には利得表やゲームの木を描画する機能があるので, 講義資料の作成にも役立つことだろう.

<br>

<font size = "5">最後に, 本書を手に取ってくれたすべての人へ.</font>
コンピュータの性能が向上し, 一般的なノートパソコンでも大規模データを収集・処理することができるようになった. 本書は, そのような「データの時代」を生きる皆さんのための新しいゲーム理論のガイ ドブックである.
私たちが本書のために開発した rgamer という R パッケージは, データ分析や可視化などのコンピュータの力を利用し, 従来のゲーム理論の学習とは一線を 画した体験を提供する.
プログラムを書いてゲームを作り, コードを書き換えてゲームを改変したり, 自分で作ったゲームで遊んだりすることによって, ゲーム理論を体験できるのだ.
さあ, rgamer をインストールして, 新しいスタイルでのエキサイティ ングなゲーム理論の学びの扉を開こう!!!

<br>

2022 年 7 月
上篠良夫・矢内勇生







