---
title: "資料作成"
author:
  - 上條良夫（早稲田大学）
  - 矢内勇生（高知工科大学）
date: "`r Sys.Date()`"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, fig.align = 'center', out.width="80%", out.height="80%")
```


rgamer を用いた講義資料などの作成方法について、簡単に紹介する。

<br>
<br>

## Powerpoint や Keynote を使用する場合

rgamer が描画した図表をコピーして貼り付ければ良い。
利得表は Viewer （default の設定では RStudio の右下のパネル） に、
最適反応やゲームの木などの図は Plots（default の設定では RStudio の右下のパネル） に表示されている。
ここから Exports でクリップボードにコピーできる。


<br>
<br>

## ioslides (HTML) で作成

外部のアプリケーションを利用せずに、
RStudio を用いて直接プレゼンテーション用の資料を作成することも可能である。
いくつか方法があるが、ioslides (HTML) で作るのが最も簡単である。

ioslides で作成できる資料は以下のようなものである。

<a href="data/test01.html"> html 形式の資料</a>

<a href="data/test01.pdf"> pdf 形式の資料</a>

このような資料を作成するには、以下の内容を R Markdown 形式 （拡張子が Rmd のファイル）で保存して、RStudio で開いて Knit ボタンを押せば良い。

<br>


````

---
title: "rgamer を用いた資料作成"
author: "Yoshio Kamijo"
date: '2023-02-12'
output: ioslides_presentation
---

`r ''````{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
`r ''````


`r ''````{r}
library(rgamer)
`r ''````


## 実行しつつコードを表示
\small

`r ''````{r echo = TRUE}
g1 <- normal_form(
  players = c("player 1", "player 2"), 
  s1 = c("C", "D"), 
  s2 = c("C", "D"),   
  payoffs1 = c(4, 5, 1, 2),
  payoffs2 = c(4, 1, 5, 2),
)

sol_g1 <- solve_nfg(g1, 
                    mark_br = FALSE, 
                    mixed = TRUE, 
                    show_table = FALSE)

`r ''````


## 利得表を表示
\small

`r ''````{r, echo = TRUE, results = 'asis'}

sol_g1$table

`r ''````


## 最適反応を表示
\small

`r ''````{r, echo = TRUE, fig.align='center'}

sol_g1$br_plot

`r ''````


## 支配関係を表示
\small

コードは表示しない

`r ''````{r}
dom(g1)
`r ''````


## 展開形ゲーム

`r ''````{r, echo = TRUE}
g2 <- seq_form(
  players = c("P1", "P2"), 
  s1 = c("C", "D"), 
  s2 = c("C", "D"),   
  payoffs1 = c(4, 5, 1, 2),
  payoffs2 = c(4, 1, 5, 2),
)
`r ''````


## ゲームの木

`r ''````{r, echo = TRUE, fig.align='center'}
g3 <- seq_extensive(g2)
`r ''````


## 向きを変える

`r ''````{r, echo = TRUE, fig.align='center'}
g3 <- seq_extensive(g2, direction = "right")
`r ''````


## 向きを変える

`r ''````{r, echo = TRUE, fig.align='center'}
g3 <- seq_extensive(g2, direction = "up")
`r ''````


## 向きを変える

`r ''````{r, echo = TRUE, fig.align='center'}
g3 <- seq_extensive(g2, direction = "vertical")
`r ''````

````

<br>

上記の Rmd ファイル。

<a href="data/test01.Rmd"> Rmd ファイル </a>

<br>

R Markdown の表記などについては以下のサイトが参考になる。

<a href="https://kazutan.github.io/kazutanR/Rmd_intro.html"> Kaztan.R の R Markdown 入門 </a>

その他にも参考になるサイトはたくさんある。


<br>
<br>

## beamer で作成

準備中




